train_data: "all"
seed: 42
data_seed: 42
num_train_epochs: 1
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
dataloader_pin_memory: False
dataloader_num_workers: 2
max_grad_norm: 1.0
fp16_opt_level: "O1"
warmup_ratio: 0.1
learning_rate: 0.0001
lr_scheduler_type: "cosine"
weight_decay: 0.01
logging_steps: 5
evaluation_strategy: "steps"
eval_steps: 50
save_strategy: "steps"
save_steps: 100
save_total_limit: 8
optim: "adamw_torch"
bf16: auto
output_dir: "./model/freeze_llm_vlm_fulldata"
overwrite_output_dir: False
report_to: "swanlab"
run_name: "freeze_llm_vlm_fulldata"
remove_unused_columns: False
gradient_checkpointing: False